kind = "web"
previewPath = "/"
title = "DrimPay"
version = "1.0.0"
id = "artifacts/drimpay"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22390

[services.development]
run = "pnpm --filter @workspace/drimpay run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/drimpay", "run", "build" ]
publicDir = "artifacts/drimpay/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22390"
BASE_PATH = "/"
